### ISSUE TITLE
Artifact is downloaded to incorrect path

### ISSUE THREAD

**Issue by rohansingh** [buildkite/agent#1035]
We have a build step that runs `buildkite-agent artifact upload /tmp/some_file.json`. In a following step, we run:

```
buildkite-agent artifact download tmp/some_file.json /tmp
```

The `INFO` logs from the command indicate that the file was downloaded successfully to `/tmp`. However, in reality, it ends up in `./tmp`. That is to say, instead of being downloaded to `/tmp`, it is downloaded to a path under the working directory.

Here is an example of this occurring, with debug output enabled:

```
2019-06-18 14:31:52 INFO   Searching for artifacts: "tmp/parse-dev-plan-c8a3072894b6dde220e112d501c91d249b4e1748.json"
--
  | 2019-06-18 14:31:52 DEBUG  GET https://agent.buildkite.com/v3/builds/dddf4bf8-cd29-4603-9f9a-dbdcd6275b38/artifacts/search?query=tmp%2Fparse-dev-plan-c8a3072894b6dde220e112d501c91d249b4e1748.json
  | 2019-06-18 14:31:52 DEBUG  ↳ GET https://agent.buildkite.com/v3/builds/dddf4bf8-cd29-4603-9f9a-dbdcd6275b38/artifacts/search?query=tmp%2Fparse-dev-plan-c8a3072894b6dde220e112d501c91d249b4e1748.json (HTTP/2.0 200 OK 87.342012ms)
  | 2019-06-18 14:31:52 INFO   Found 1 artifacts. Starting to download to: /tmp
  | 2019-06-18 14:31:52 DEBUG  Downloading https://s3.amazonaws.com/buildkiteartifacts.com/<REDACTED> to tmp/parse-dev-plan-c8a3072894b6dde220e112d501c91d249b4e1748.json
  | 2019-06-18 14:31:52 INFO   Successfully downloaded "tmp/parse-dev-plan-c8a3072894b6dde220e112d501c91d249b4e1748.json" 3 bytes
```

The artifact is downloaded successfully, but to a new `tmp` directory that is created within the working directory.

Not sure if this is related to #694.

**Comment by lox** [comment]
That's really perplexing @rohansingh! At present behaviour for absolute paths for artifacts is undefined, but clearly needs some work.

**Comment by Helcaraxan** [comment]
While digging through the `agent` code to ensure I was using it correctly I stumbled on the code that actually triggers this unexpected (and undefined) behaviour.

I've taken the liberty to put up a PR (#1121) that addresses it.

**Comment by pda** [comment]
This is an interesting one. I'm going to make a comparison to `tar` and call it expected behaviour.

Here's your example case:

```sh
buildkite-agent artifact upload /tmp/some_file.json

rm /tmp/some_file.json

buildkite-agent artifact download tmp/some_file.json /tmp
# Found 1 artifacts. Starting to download to: /tmp
# Downloading https://... to tmp/some_file.json
# Successfully downloaded "tmp/some_file.json" 3 bytes

tree /tmp
# /tmp
# └── tmp
#     └── some_file.json
```

(Aside, regarding the logs: I think they're saying "downloading `tmp/some_file.json` _within_ `/tmp`", so it makes sense the result is `/tmp/tmp/some_file.json`, just like "downloading `hello/world.json` within `/tmp`" would result in `/tmp/hello/world.json`)

Let's name the parameters:

```sh
FILE="/tmp/some_file.json"
DIR="/tmp"
MEMBER="tmp/some_file.json"
```

So now your commands are:

```
buildkite-agent artifact upload "$FILE"
rm "$FILE"
buildkite-agent artifact download "$MEMBER" "$DIR"
```

I think that's analogous to:

```sh
tar -cf artifacts.tar "$FILE"
rm "$FILE"
tar -C "$DIR" -xf artifacts.tar "MEMBER"
```

Here's what we get when we run that:

```sh
tar -cf artifacts.tar /tmp/some_file.json
# tar: Removing leading `/' from member names

rm /tmp/some_file.json

tar -C /tmp -xvf artifacts.tar
# tmp/some_file.json

tree /tmp
# /tmp
# └── tmp
#     └── some_file.json
```

Same! I don't know that we deliberately copied tar's behaviour, but I think it's nice. As long as we don't end up with as many options as tar!

---

Now to flip the problem; how would we solve this in `tar`?

We could extract to `/` instead of `/tmp` :grimacing: 

```
tar -C / -xf artifacts.tar tmp/some_file.json
tree /tmp
# /tmp
# └── some_file.json
```

... that works, but it's scary extracting to `/`, even if we are specifying only `tmp/some_file.json` be extracted/downloaded.

We could use `--strip-components=N` to remove the number of directory components matching our extraction directory, i.e. 1 for `/tmp`; 

```
tar -C /tmp --strip-components=1 -xf artifacts.tar tmp/some_file.json
tree /tmp
# /tmp
#└── some_file.json
```

... that works, but it would require adding a confusing option to `buildkite-agent artifact upload`.

Maybe it's best to change directory (`-C <dir>` in `tar`) before both sides of the operation:

```
tar -C /tmp -cf artifacts-rel.tar some_file.json

tar -C /tmp -xf artifacts-rel.tar some_file.json

tree /tmp
# /tmp
# └── some_file.json
```

`buildkite-agent artifact` doesn't have a `-C`, but you can always `cd` before running it.

```sh
(cd /tmp && buildkite-agent artifact upload some_file.json)

rm /tmp/some_file.json

(cd /tmp && buildkite-agent artifact download some_file.json .)

tree /tmp
# /tmp
# └── some_file.json
```

The downside is the server-side artifact path loses its `tmp/` namespace and becomes `some_file.json` rather than `tmp/some_file.json`.

---

Anyway, I think we're happy with artifact upload/download matching tar behaviour; if you can think of any improvements (even just docs / log messages) that fit within that analogy, let us know!

**Comment by pda** [comment]
(happy to re-open if there's more thoughts on this)
