### ISSUE TITLE
Expose an endpoint to use as a healthcheck for the build agent

### ISSUE THREAD

**Issue by matthewkmayer** [buildkite/agent#111]
(AWS focused) use case: if running a fleet of elastic agents in an autoscaling group with an elastic load balancer for healthchecks, an HTTP endpoint on an instance can be used to determine if the agent is still available.

For example, if an agent crashes, the endpoint would stop responding and the instance would be terminated.  A new instance would be spun up by the ASG.

This would enable easy horizontal scaling on smaller instances.

Perhaps check an environment variable such as BUILDKITE_EXPOSE_HTTP_ENDPOINT and if set to true, run http.ListenAndServe.

**Comment by toolmantim** [comment]
From Slack…

> The ELB healthcheck dictates a single endpoint to check, so limits to a single build agent on an instance with this feature.
>
> Hence the preference towards many smaller instances.
>
> Limits liability in case an availability zone goes down.

**Comment by toolmantim** [comment]
I think it'd make sense to include a port argument if we were to add this… just to support multiple agents on the one machine.

**Comment by matthewkmayer** [comment]
There's the existing API for polling registered agents: https://buildkite.com/docs/api/agents .  

If that was to be used, each instance would have to be running a watchdog process that polls the GET agents endpoint, matches the hostname with its instance hostname and check the status.  If not a healthy state, report back to AWS the instance is unhealthy.

I'd greatly prefer an HTTP endpoint exposed and let the ELB do the work.

**Comment by keithpitt** [comment]
I don't think we'll put this functionality directly into the agent (I try to keep the agent as dumb as possible). In saying that, I still think the idea in general is good! I just quickly wrote a tool that should help us!

https://github.com/buildkite/elb-healthcheck-pid

Just spin this tool up along side the agent and give it the agent's PID, and it'll give you an endpoint that you can monitor in ELB.

What do you think of this approach? (btw, I wrote this in a few hours and some local testing, so I haven't done any thorough testing yet, but it seems to work!)

**Comment by matthewkmayer** [comment]
I'm not sold on doing a health check outside the process: the signal 0 used by the elb-healthcheck-pid project only tells us if the PID exists and we can send a signal to it.  It tells us nothing about its state.

How can we determine if the agent process is unresponsive or crashed?  Embedding an http server is one way, or writing to a log as a heartbeat, etc...  Not sold we can get enough information outside the process.

**Comment by keithpitt** [comment]
So here are some things that come to mind, and I may be completely wrong on some of them :) - but may be worth talking about! I'll talk about each one:

>    agent process is unresponsive

I suppose an important question here is: what is "unresponsive"? It's not just accepting any work now? Or no longer communicating with Buildkite?

If the thread that's doing the actual work somehow gets stuck, but the thread that is running the HTTP server is still running fine, this could give funky results. So we'd need to handle that some how.

>    agent crashed

Because of the way Go handles errors, it makes actually crashing the program very difficult (unless you call `panic`) which we don't do anywhere. If the agent crashes, wouldn't it be easier for the OS to just restart it? Instead of taking it out of the group? `upstart`, `monit`, `inspeqtor` have already solved this problem.

Touch wood :evergreen_tree: we've never had a report that an agent has panic'd and crashed. One of our customers has an auto-scaling EC2 group setup with our agents. They pipe their build queues into CloudWatch, and it automatically scales up/down how many agents they have running at once. It's working great for them, and they've never had a problem with agents getting stuck on their end.

Buildkite already has a mechanism to detect agents that have crashed. We already take them out of the pool of agents when we don't hear from them in a while - so the only thing we need to solve now is taking it out of your server rotation.

#### Other approaches

Just like you're not sold on the pid monitor, I'm not sold that banging a HTTP server in the agent is the best solution :) Just like we don't do our down daemonizing (because that's a solved problem from other tools). If enough people wanted it - then we can revisit. But I think we together we may be able to find a solution that should work for your use case! :dancers: 

So, here are some other ideas:

1. When Buildkite detects an agent as missing, we send a webhook to you with details about which one was lost, and you remove that server from the group using the AWS API. Our agents check in ever 3-5 seconds, so if we haven't heard from the agent in a while, we assume it's gone. We can let you know when this happens.

   I think this would be a good approach, because once you start accepting those hooks, you can start pumping your build queue information into Cloudwatch to spin up/down instances.

2. Using one of the monitoring tools I mentioned, detect if the agent crashes/stops, and then `touch /var/www/broken.txt` and you have some nginx rules that detect if the `broken.txt` is present, and starts returning a 500.

```
if (-f $document_root/broken.txt) {
  return 500;
}
```

3. Again, using one of the tools I mentioned above, when you detect a fatal crash, and it can't be restarted, call `sudo shutdown now` - which should take it out of rotation, right?

4. You rotate your servers every 12-24 hours, so if you have any crashed agents hanging around, they'll just get cleaned up by the restart (crappy approach, but somewhat solves the problem).

#### Other tools

Can we learn anything from how other tools do this? How does AWS recommend you remove servers from a scaling group? I tried to find some docs on it, but it seems they just let you handle that stuff yourself.

**Comment by matthewkmayer** [comment]
An unresponsive agent would be one not accepting any new work or is hung running a job for a long time.  Long time being undefined for now, but there's probably a rough guideline to use, such as a step not finishing in 30 minutes.

It sounds like the big question is how to notify the infrastructure running the build agents to terminate the instance with an agent in a bad state.  The four options you outlined are ways to handle that.  My thoughts:

1. A webhook receiver would mean each customer would need to make their own infrastructure to accept the call and sort out the logic to find which instance to terminate.  Adds a fair amount of complexity and each customer would have to make their own stack.  Maybe provide a solution that receives the webhook and allows a shell command to be run on reception?  That way AWS users can use that to implement the shutdown command mentioned in option three.

2. A watchdog process along with an nginx process adds complexity to each instance.  It smells a bit and only handles crashes of the process.

3. A watchdog process that can shut down the instance sounds simpler.  This means the autoscaling group can be made without using an ELB, thus no need for an ELB healthcheck.  Of the four options this one appeals the most.  Still only handles the agent crashing though.

4. Cycling all instances regardless of agent status seems a good way to waste money and bandwidth. :)

I do hear you about the stability of the golang process - explicit error handling makes crashes less likely, but there could be other factors that nix the process.  Kernel bugs, instance running out of resources such as memory and starts killing processes, etc...  And yes, there could be a state where the http server goroutines work fine but the "worker" goroutines can be hung up.

I've requested someone weigh in on the canonical way of removing servers from an ASG.

**Comment by scottvidmar** [comment]
AWS AutoScaling really manages host swaps for you. I can think of two distinct ways off the top of my head that would give you the desired effect of swapping a host out of the group:

(1) The AutoScaling service exposes an API to manage instance health, SetInstanceHealth (http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_SetInstanceHealth.html), so you can manually set it to unhealthy. This will cause the AutoScaling group to replace the unhealthy node. Cycling instances in and out of the logical group of instances is handled by AutoScaling. The major part of it is getting agents "registered" back with the "master" service on instance boot. That's just a matter of configuring the registration with the boot.

(2) Maintain a fixed AutoScaling group size, and just either shut the instance down from within the OS, or call the EC2 terminateInstances API. This would force the ASG to normalize by launching a replacement.

Option #1 is far more flexible, as it allows you to scale the fleet in and out, without risk of behavioral changes regarding desired capacity vs. current capacity, etc... if AWS decided to modify the functionality under the covers. It also gets things into a less wasteful mode of operation, and unleashes more cost-effective workflows. 

Of course, the effectiveness of this assumes that the health and state of the agent can be accurately determined/interrogated beyond "is the process in a running state and not hung on a task?"

**Comment by matthewkmayer** [comment]
Howdy guys.  Any more thoughts on this?

**Comment by keithpitt** [comment]
Hey @matthewkmayer - sorry - we've been flat out prepping for the new agent release. We've been deep in writing documentation lately - so we haven't had a chance to start thinking about new features. How's the agent been tracking without this feature for you? Is it ok, or have you hit some snags?

**Comment by matthewkmayer** [comment]
We've not had a chance to pick this up again ourselves, but we still desire an external health check.

**Comment by keithpitt** [comment]
I've had a think about this some more, and the solution we want to support for now is to go with the watchdog process, like the one I created before: https://github.com/buildkite/elb-healthcheck-pid

There are too many variables to determine if an agent is "hung", and because of the agent's concurrent nature, we would have to do some drastic rewrites of it's internals, that we have no plans to do at this stage. If a goroutine does get stuck or blocks indefinitely due to a bug, the healthcheck HTTP endpoint will continue to function correctly, and the server will remain in rotation.

If a user _does_ notice something wrong, then can hit the "Stop" button on the agent. We can trigger a webhook if someone does do this so you can hook it up to ELB to take that server out of rotation.

We've not had reports of hung or crashed agents before, touch :evergreen_tree:.

If jobs get hung, users can use the _Automatic Timeout_ feature to have jobs automatically killed after a certain period of time. If a job does hang, then the job should just get cancelled, no need to remove the server from the fleet.

If the agent crashes, `upstart` will take care of that. If it fails to start, you can user other tooling to notify ELB and take that server out of rotation. No need to remake that stuff in the agent. You'd probably not want to take the server out of the fleet anyway, so you can debug what's going wrong.

It's also common and recommended to run multiple agents on the same machine, which would add another layer of complexity around this.

Sorry If I've wasted your time on this @matthewkmayer! If there's more demand for this sort of feature from others, we can take another look at it down the track. We've got some customers running agents across entire AWS fleets, and to our knowledge there's been no problems related to the agent.

If there's any information that we can expose from the agent or any webhooks that we can trigger that would make the integration on your side easier, we'd be happy to look into that!

**Comment by blueimp** [comment]
Sorry to dig up an old thread.

Would it be possible to expose a command like `buildkite-agent status`?
I would expect it to return a successful status if it has an active connection to the buildkite API.

That would be quite helpful in implementing such a health check endpoint.
In my case, I plan to simply run the busybox httpd daemon on the same machine (same docker container in my case), which exposes a cgi script as health endpoint that would then call the aforementioned command.

**Comment by philwo** [comment]
FYI, https://github.com/buildkite/agent/pull/1066 implements this. :)
