### ISSUE TITLE
FATAL  Failed to get meta-data: POST https://agent.buildkite.com/v3/jobs/../data/get: 404 No key "status" found

### ISSUE THREAD

**Issue by jerrymarino** [buildkite/agent#1227]
It looks like this endpoint started to return a 404, and the agent doesn't expect that.

This break scripts that do something like this:
```
STATUS=$(buildkite-agent meta-data get "status")
echo "Build finished with $STATUS"
if [[ $STATUS == "fail" ]]; then
  exit
fi
```

**Comment by chloeruka** [comment]
Hi Jerry, I'd say this is expected behaviour [according to the documentation for `buildkite-agent meta-data`](https://buildkite.com/docs/agent/v3/cli-meta-data#getting-data) if the key did not exist in meta-data at the time it was asked for.

You could fix the above script by setting a default value like so:
```sh
STATUS=$(buildkite-agent meta-data get "status" --default "fail")
echo "Build finished with $STATUS"
if [[ $STATUS == "fail" ]]; then
  exit
fi
```

In the above case, the default value of "fail" will be hydrated into `$STATUS` when there's no "status" key available (e.g. the 404 error you described). This is assuming in the event of no-data it's treated as a failure case. You could consider also using [`buildkite-agent meta-data exists`](https://buildkite.com/docs/agent/v3/cli-meta-data#checking-if-data-exists) to check the key before use.
