### ISSUE TITLE
[Feature Request] Clean Checkout should also allow reset of modified files

### ISSUE THREAD

**Issue by derekbrokeit** [buildkite/agent#1296]
Per the documentation the following environment variables can be used to configure the agent for checkout.

- BUILDKITE_CLEAN_CHECKOUT
- BUILDKITE_GIT_CLEAN_FLAGS

Given a git repository, this will remove untracked files and can be configured to include directories as well. There is a potential that a poorly setup pipeline can also cause tracked files to change, which clean will not correct. These files will remain modified in the repository, which could have negative side effects such as modified behavior or merge-conflicts at checkout.

It would be good to also perform or allow hooks for performing `git reset $BUILDKITE_GIT_RESET_FLAGS` at the checkout phase to eliminate these potential side effects from affecting the checkout phase.

**Comment by sj26** [comment]
Hi @derekbrokeit,

It sounds like there are some hard learned lessons behind this request — sorry! Any chance you could share the specific problems you've encountered, and how you imagine these flags might work to solve them?

To clarify, `BUILDKITE_CLEAN_CHECKOUT=true` will completely remove a working tree, including tracked and untracked files, and then create a completely fresh checkout for the build. There should be no way for a modified file to sneak through here. If you've found a way, then it's a bug.

Otherwise, the agent does a clone or fetch, then a forced git checkout, which should make sure that all tracked files are reset to the proper contents at the head commit, and then a git clean, which with the default configured flags will remove any untracked files and directories, including any ignored files. If you've seen different behaviour here then again it is a bug, and we'd love to hear about it.

**Comment by sj26** [comment]
If you want to, you can also add an agent `post-checkout` hook with any `git reset ...` logic you require. :-)

**Comment by derekbrokeit** [comment]
Thanks for your comment @sj26, 

The main reason I can envision wanting to use git-reset would be to ensure that the local repo index is cleared of any anomalous files or commits. For example, you can force a `git reset --hard`, so you have confidence that the repository at this particular worker has the expected history and file structure.

Thank you, it wasn't entirely clear to me if `BUILDKITE_CLEAN_CHECKOUT` removes the directory or performs a git-clean. If it removes the entire directory, that would certainly fix the issue described, but it would cause a different set of problems for my use case. For example, if a repository is very large including many LFS objects or network retrieved objects, it would need to be downloaded again causing significant network load on whatever servers house the cached items. I wasn't using `BUILDKITE_CLEAN_CHECKOUT` for this reason. 

I was not seeing a forced checkout in my pipeline, but I will have to look to see if that is disabled for some reason. I suppose a forced checkout would similarly correct the behavior that I observed. I will look at applying a correction to the `post-checkout` hook for now to ensure we at least correct it on our end.

**Comment by sj26** [comment]
Hmm, yeah interesting. The agent is designed so that every job should run without any anomalous files or commits. If there are some, then it's a bug. It sounds like you've hit a very specific problem. Are you able to send us some details to support@buildkite.com including a build link so we can take a look? We'll figure it out for you there.

In the meantime, I'm going to close this issue. It's a good idea, but I'm not sure is the right solution here.
