### ISSUE TITLE
3.23.1 with git-mirrors repeatedly fails to clone repo: "fatal: Couldn't find remote ref"

### ISSUE THREAD

**Issue by fweikert** [buildkite/agent#1303]
We deployed new CI workers with agent v3.23.1 today, and immediately saw some builds failing during git clone:

```
fatal: Couldn't find remote ref <some ref>
 ⚠️ Warning: Checkout failed! exit status 128 (Attempt 3/3 Retrying in 2s)
```

Examples:
- https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/6940#38fc9cd4-064d-4085-a2c8-2a934bcf5b7e
- https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/6941#c95a2e10-2460-4bac-8342-57313871e888

We're using the git-mirrors experiment.
Downgrading to v3.22.1 solved the problem for now.

Maybe related to #1299 ?

**Comment by fweikert** [comment]
cc @philwo

**Comment by sj26** [comment]
Hi folks! I think this might be a different issue. It looks like the fetch has changed from a general update of all refs:
https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/6941#eb5be682-b3b4-4475-b625-626c23bcabd4/32-39

to an optimised fetch of a specific ref:
https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/6940#38fc9cd4-064d-4085-a2c8-2a934bcf5b7e/32-39

In this case the optimization has broken your build — sorry!

It looks like your ref is invaild — it contains a colon — but was incidentally working because we fetched everything and checked out the commit sha:
https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/6941#eb5be682-b3b4-4475-b625-626c23bcabd4/32-73

Can you supply a valid ref/branch name for you builds?

**Comment by philwo** [comment]
Hi @sj26,

These builds are triggered by Buildkite itself (via the GitHub pull-request webhook), so I would assume that the invalid refspec comes from Buildkite? I don't see any of our own custom code running before that checkout step. 🤔

**Comment by philwo** [comment]
Could it be caused by this feature, which we have enabled for the pipeline?

<img width="805" alt="Screenshot 2020-09-17 at 13 48 25" src="https://user-images.githubusercontent.com/504652/93466443-88d74100-f8ec-11ea-90d2-76d06d2b454c.png">

**Comment by sj26** [comment]
Oh yes, sorry, that'll be why — sorry I didn't put that together!

Yes this sounds like a bug, then. 😞

**Comment by sj26** [comment]
I think this was introduced in #1112.

**Comment by sj26** [comment]
Sorry, I think for the moment your workflow is incompatible with git mirrors experimental feature, at least on v3.23.1. I've written this up as a new github issue:

https://github.com/buildkite/agent/issues/1305

Please subscribe over there to track.

**Comment by keithduncan** [comment]
Hi folks :wave: I’m cleaning up old issues and it looks like this was fixed with https://github.com/buildkite/agent/pull/1308. I’m going to close this issue but if I have missed something and there is still an issue occurring please don’t hesitate to leave a comment or re-open the issue. Thank you again for reporting this issue :bow:
