### ISSUE TITLE
[aws mac1.metal] buildkite agents not getting ec2 metadata tags

### ISSUE THREAD

**Issue by OliverKoo** [buildkite/agent#1420]
**Environment**

- using buildkite-agent v.3.29
- have `tags-from-ec2-tags=true` and `tags-from-ec2` both set to true and `wait-for-ec2-tags-timeout=300s` in config.
- launching the agent via launchctl on mac1.metal ec2 instance (Big Sur).

**Issue** 

buildkite-agent is set to launch when machine boot. it however does not get the ec2 metadata tags (aws:instance-id, aws:instance-type...etc). Looking at the log I see that it did indeed wait for ec2-tags (the tag I set) but not the metadata tags. fetch retried 5 times then gave up 

```
2021-04-24 00:37:23 WARN   RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/instance-id": dial tcp 169.254.169.254:80: connect: network is unreachable (Attempt 5/5 Retrying in 1.465s)
2021-04-24 00:37:24 ERROR  Failed to fetch EC2 meta-data: RequestError: send request failed
```

If I unload the daemon and reload it (restart the agent) then I get all the tags. I am suspecting ec2-metadata tags was not ready yet during fetch)

**Ask**

Is there an equivalent of  `wait-for-ec2-tags-timeout` for metadata tags? seems like the timeout only applies to ec2 tags

**Comment by sj26** [comment]
Sorry @OliverKoo, it looks like we only use that timeout for the resource tags:
https://github.com/buildkite/agent/blob/693b319b4b892e84e2e66daece8a84acd4d1c053/agent/tags.go#L150

I think it'd be totally reasonable to add an equivalent setting for the ec2 meta-data too. If you're keen, you could follow the same pattern and apply it here and submit a pull request:
https://github.com/buildkite/agent/blob/693b319b4b892e84e2e66daece8a84acd4d1c053/agent/tags.go#L103

Otherwise we'll get to it when we can. :-)

**Comment by OliverKoo** [comment]
Here ya go - https://github.com/buildkite/agent/pull/1425
