### ISSUE TITLE
Calling Windows programs, from within WSL2 hangs agent

### ISSUE THREAD

**Issue by dchw** [buildkite/agent#1447]
I am using the Linux agent, installed under WSL2 on a Windows 10 box. From what I can tell, invoking _any_ Windows executable within my build causes the whole thing to freeze.

To reproduce, a simple command might be `xcopy.exe /?` to print the help text. Notably, everything I have tried outside the buildkite runner has worked, even when wrapped in a shell script.

I understand if this is low priority. I... didn't expect it to work. But I thought I would bring it up in case you wanted to also warn about this in your docs?

**Comment by keithduncan** [comment]
Some previous customers have reported hanging issues when executing Windows binaries from Buildkite WSL2 environment when setting the `WSLENV` environment variable to include all `BUILDKITE_*` environment variables. Does that sound like something that could be causing this issue? If not, could you tell us more about your agent environment and we’ll try to reproduce this. Thanks!

**Comment by dchw** [comment]
I am not setting `WSLENV` directly. Perhaps its implied?

We start the agent with a simple `wsl <path_to_agent> start` command, in a powershell script, from a scheduled task that runs at boot (use this over a service to get some additional cleanup & etc done before the agent is ready).

Configuration is how it comes out of the box, with a single hook added to export a non-buildkite environment variable. The hook is a simple bash script.

**Comment by keithduncan** [comment]
I’ve asked around but I’m afraid we don’t have enough experience with WSL(2) to offer support for this use case 😢. We are interested in learning more about WSL2 to better support customers running the agent in this way, and would be curious to learn what the issue is if you are able to figure it out.

I’ll leave this issue open for now to see if any one else coming across it has ideas what what could be happening. Sorry I can’t be of more assistance!

**Comment by dchw** [comment]
@keithduncan I updated the agent on this box from 3.26 -> 3.30. Somewhere along the line this issue appears to have been fixed, FWIW. Thanks for your effort and attention to this issue?
