### ISSUE TITLE
`environment` hook not called before `agent-shutdown` 

### ISSUE THREAD

**Issue by ahmedwonolo** [buildkite/agent#1625]
I have `environment` hook setting some environment variables that are passed into the `agent-shutdown` script.
Looks like that `agent-shutdown` doesn't have these environment variables set and hence it fails. 
The same script works fine when called within `pre-exit` hook.
Thanks.

**Comment by ahmedwonolo** [comment]
opened in error.

**Comment by ahmedwonolo** [comment]
actually, reopening it since it doesn't work

**Comment by moskyb** [comment]
kia ora @ahmedwonolo! I'm not 100% sure what's going on with the state of this issue, but at current, this is working as intended. The `environment` hook is intended so that your agent can pull in information it needs when it runs jobs; this is intentionally kept separate from the `agent-shutdown` hook, which has nothing to do with jobs. The `pre-exit` hook that you mention also exists in the context of a job, so the `environment` hook has already been called when the `pre-exit` hook runs.

If you really need the environment variables from the `environment` hook in your `agent-shutdown` hook, i'd recommend refactoring the `agent-shutdown` hook so that it fetches the env vars it needs.

Hope this helps! Happy to chat more if you want :)
