### ISSUE TITLE
Make location of repository hooks configurable

### ISSUE THREAD

**Issue by GMNGeoffrey** [buildkite/agent#1668]
**Is your feature request related to a problem? Please describe.**

In our project, we put all our build tool configuration stuff in a top-level `build_tools` directory. This helps to keep infrastructure organized separately from the core source code and avoids cluttering the landing page when someone first visits the repository. It looks like Buildkite repository hooks have to go in “.buildkite/hooks” at the root of the repo ([docs](https://buildkite.com/docs/agent/v3/hooks#hook-locations:~:text=from%20any%20pipeline.-,Repository%20hooks,-%2D%20these%20exist%20in)). I see this is currently hardcoded in the [agent bootstrap](https://github.com/buildkite/agent/blob/1598e4ff55/bootstrap/bootstrap.go#L390)

**Describe the solution you'd like**

Add a configuration parameter to the agent to specify the location to look for repository hooks.

**Describe alternatives you've considered**

Do nothing. Having a standardized location across repos is better.

**Additional context**

Forum discussion: https://forum.buildkite.community/t/custom-repository-hook-location/2081

**Comment by pda** [comment]
Thanks @GMNGeoffrey — that's an interesting one.

We're not sure adding an agent option for this makes sense, because it seems like a per-pipeline / per-repository thing. Your organization may have this standard across all pipelines/repos, but there could exist orgs that need repo hooks in different places for different repos.

I wonder if it would make sense as a config option in the pipeline YAML, since that's in the right scope. But we don't really have config like this in that YAML currently, so that would be a substantial change.

I was going to suggest using symlinks as a workaround, but I see you're already doing that :)

I think we'll close this for now, but we will track it as a feature request for future consideration.
