### ISSUE TITLE
Should we remove -g when invoking tini for the docker image?

### ISSUE THREAD

**Issue by com6056** [buildkite/agent#1758]
**Is your feature request related to a problem? Please describe.**

Right now, the buildkite docker image invokes tini with the `-g` option, which signals all children processes when a signal is received:
https://github.com/krallin/tini#process-group-killing
>With the -g option, Tini kills the child process group , so that every process in the group gets the signal. This corresponds more closely to what happens when you do ctrl-C etc. in a terminal: The signal is sent to the foreground process group.

**Describe the solution you'd like**

Do we want to remove this so jobs have a chance to finish before they receive the signal from buildkite itself when the grace period expires?

**Comment by pda** [comment]
Interesting!

So our docker entrypoint.sh runs under `#!/bin/bash` as PID 1 and does this:

```sh
exec /sbin/tini -g -- ssh-env-config.sh /usr/local/bin/buildkite-agent "$@"
```

PID 1 should be _replaced_ by `tini` via the `exec` call, so that's good so far. And it runs `ssh-env-config.sh` as a subprocess (PID > 1, PPID == 1)

`ssh-env-config.sh` comes from https://github.com/buildkite/docker-ssh-env-config and runs via `#!/bin/bash`. Neither the [README](https://github.com/buildkite/docker-ssh-env-config#readme) nor a [search through the repo/issues/etc](https://github.com/buildkite/docker-ssh-env-config/search?q=signal) mention anything about signal handling, so it may not have been explicitly considered.

However `ssh-env-config.sh` ends in `[[ $1 ]] && exec "$@"`, and that `exec` call should again replace the `/bin/bash` process with `/usr/local/bin/buildkite-agent` as a direct subprocess of `/sbin/tini`.

Let's validate that in a `buildkite/agent:alpine` container I have running:

```
$ docker exec 4ac1948e2ee2 ps -o ppid,pid,args
PPID  PID   COMMAND
    0     1 /sbin/tini -g -- ssh-env-config.sh /usr/local/bin/buildkite-agent start
    1     7 /usr/local/bin/buildkite-agent start
```

Certainly looks like tini would pass the signal to buildkite-agent even without the `-g` 👍🏼

I also took a look through commit history, the first mention of `/sbin/tini` was in 88e949da20fb105eb2fc75806ec05db283deaba1 and it arrived with `-g`; there's no evidence of it being added for a particular reason or to fix a particular issue.

So, I think you're right, we should drop the `-g`.

**Comment by pda** [comment]
@com6056 https://github.com/buildkite/agent/releases/tag/v3.39.0 includes #1763 to fix this 🚀
