### ISSUE TITLE
Graceful stop from CLI

### ISSUE THREAD

**Issue by es** [buildkite/agent#176]
Many times it's useful to be able to gracefully shutdown agents from the CLI when ssh'd into a box

@keithpitt

**Comment by byroot** [comment]
As an example: Nginx use the `QUIT` signal for graceful shutdown and `TERM` / `INT` for quick shuftdown: http://wiki.nginx.org/CommandLine#Stopping_or_Restarting_Nginx

**Comment by lox** [comment]
It would be great to be able to either shutdown after the current job has finished, or alternately shutdown immediately and have the job sent to another agent without generating an error.

**Comment by keithpitt** [comment]
@es just looking at this again, and I forgot what it was :) It's essentially to send a signal to the agent, so when it's finished it's current job, it'll exit?

**Comment by lox** [comment]
Yup, for example for auto-scaling. Even better would be a way to stop it immediately and re-send the job to another agent ;)

**Comment by keithpitt** [comment]
Cool! Graceful shutdown is back! https://github.com/buildkite/agent/commit/62d2feb28dcab5b15e335395943c2cf3c9c90c4b#diff-ce9d59e4030c50e8a42c94202dbb9c82R69 This will be available in the next beta that I'll push out in the next hour or so. 

Because there are 2 types of graceful shutdown (kill job, or wait for job) it was hard choosing which signals should do what. So `TERM` and `INT` will wait for the current job to finish before disconnecting. `QUIT` will cancel the current job, then disconnect. Hopefully that's not too confusing :\ If it is, or you disagree, I can change :)

For your case @lox, the resend the job to another agent gear is a little tricky and work will need to be done on the Buildkite side of things, but I've come up with a short term solution for the "one shot" jobs. I've added the agents PID as an environment variable to the agent: https://github.com/buildkite/agent/commit/62d2feb28dcab5b15e335395943c2cf3c9c90c4b#diff-fb08d3fc4fc6480db9e28ae0e8e21614R157

So you could have a `post-command` hook that does this:

```
kill -s INT $BUILDKITE_AGENT_PID
```

Which will cause the agent to disconnect after finishing the current job.
