### ISSUE TITLE
Allow artifacts download when job fails

### ISSUE THREAD

**Issue by charleskawczynski** [buildkite/agent#1825]
**Is your feature request related to a problem? Please describe.**
Over at [CliMA](https://github.com/CliMA), we use buildkite for simulating physics (e.g., fluid flows). We export our simulated results in-situ, so, we have artifacts that we'd like to see whether the simulation completes or crashes. When it crashes, we'd like for the job to fail, but it would also be helpful to still see the output. However, buildkite doesn't seem to upload artifacts for failed jobs.

It would be really helpful if buildkite could allow some option for uploading artifacts even for failed jobs

**Describe the solution you'd like**

It'd be nice if this were the default behavior, but I imagine some users may depend on the existing behavior.

But, it'd be helpful if there was a "`soft_upload`" meta option for `artifact_paths`:
```
        artifact_paths: "output/*"
            soft_upload: true
```
that would persist in grabbing uploads even when the job fails.

**Describe alternatives you've considered**
I suppose we could add dependent jobs for every job that uploads the artifacts, but this seems like a major kludge

**Additional context**
N/A

**Comment by pda** [comment]
Howdy @charleskawczynski 👋🏼

It sounds like you have a pipeline using `artifact_paths`, but you're not seeing those uploaded when the job crashes/fails.

I _believe_ the agent does attempt to upload `artifact_paths` even when the command fails.

Here's some code comment describing that:

https://github.com/buildkite/agent/blob/7022d6f41d338d070aefee3ac6a859aa8fff196b/bootstrap/bootstrap.go#L150-L164

And the actual upload, which seems to happen for all command steps regardless of exit status:

https://github.com/buildkite/agent/blob/7022d6f41d338d070aefee3ac6a859aa8fff196b/bootstrap/bootstrap.go#L175

Note that an error during phases prior to the command running (i.e. `checkout` or `plugin`) _will_ prevent the artifacts being uploaded. So if your work is happening in a plugin, perhaps that's what's going on?

Or…

Generally the process tree of a running job looks like this:

```
buildkite-agent start
└── buildkite-agent bootstrap
    └── bash (“script wrapper”)
        └── your command
            ├── your
            ├── command's
            └── subprocesses
```

The bash “script wrapper” propagates the exit status of your command to the bootstrap process, which propagates it to the main `buildkite-agent start` runner, and determines the pass/fail for the step. The `artifact_paths` uploading happens inside `buildkite-agent bootstrap` regardless of exit status, so any exit/crash of your command shouldn't prevent it.

I wonder if the entire `buildkite-agent bootstrap` is being [OOM](https://en.wikipedia.org/wiki/Out_of_memory)-killed by the kernel in your crash scenario? Or is otherwise incapable of continuing execution due to your crashing command using all the system resources (RAM/CPU/storage/something). That would perhaps result in `artifact_paths` not being uploaded.

I hope there's some useful hints in there, and thanks for helping figure out the climate!

**Comment by charleskawczynski** [comment]
Hmm, I'm kicking myself for not uploading a particular build. I can't seem to find the build where this was a problem, and other builds I'm looking at suggest that there was a bug in our flow control, and that we just never saved data to the artifacts path. Closing for now. Thanks for looking into this, but sorry for the noise!
