### ISSUE TITLE
Buildkite Agent 3.43.x changed tini version & path

### ISSUE THREAD

**Issue by willhughes-au** [buildkite/agent#1928]
Buildkite Agent v3.43.x has changed the path and version of tini. 

Buildkite Agent 3.42.0 has tini 0.19.0 available at /sbin/tini:

```
$ docker run -it --entrypoint=/bin/sh buildkite/agent:3.42.0-ubuntu
# /sbin/tini
tini (tini version 0.19.0 - git.de40ad0)
Usage: tini [OPTIONS] PROGRAM -- [ARGS] | --version
```

In 3.43.1 that path is no longer there, and an older version of tini is at another path.

```
$ docker run -it --entrypoint=/bin/sh buildkite/agent:3.43.1-ubuntu
# /sbin/tini
/bin/sh: 1: /sbin/tini: not found
# which tini
/usr/bin/tini
# tini 
tini (tini version 0.18.0)
Usage: tini [OPTIONS] PROGRAM -- [ARGS] | --version
```

**Comment by triarius** [comment]
Hi @willhughes-au. Thanks for reporting this to us. It does look like this was caused by a recent changed that we made to the agent's ubuntu-20.04 docker image to install `tini` from the ubuntu repos rather than downloading the binary from github. We consider installing packages from a distribution's repositories to be the better practice, so we are not keen to revert this change.

[We can create a symlink for you to restore the old path](https://github.com/buildkite/agent/pull/1934) and release a new version. In the meantime, it should be quite straightforward to work around this by using the new path, or even just `tini` to execute it instead. For example:
```
docker run -it --entrypoint tini buildkite/agent:3.43.1-ubuntu -- buildkite-agent --version
```
should give you the output:
```
buildkite-agent version 3.43.1, build x
```

Having said that, if you use the default entrypoint - located at /usr/local/bin/buildkite-agent-entrypoint`, it should already be invoking `tini` at the correct path. So I am a little curious if:
1. There is a particular reason why you need the path to be `/sbin/tini` and not `/usr/bin/tini`?
2. There is a particular reason why the default entrypoint, is not working for you?


As for the version being v0.18.0, that is the latest version in the [ubuntu-20.04 repositories](https://packages.ubuntu.com/focal/tini). After reading both the [changelog](https://github.com/krallin/tini/releases/tag/v0.19.0) and the [commits](https://github.com/krallin/tini/compare/v0.18.0...v0.19.0) between v0.18.0 and v0.19.0, it seems to me that v0.19.0 does not introduce any new features, just some changes to documentation, CI, and an error message. If there is some specific reason you need version v0.19.0, please let us know.

**Comment by triarius** [comment]
> Being at a particular path isn't important, being consistent between versions is. I wasn't able to find a common tini path in 3.42.x and 3.43.x, and I didn't want to have vNext perhaps change the path back again.

Fair point. We will have a fix out soon. In the meantime, are you unable to work around it by just invoking it as `tini`? For example:
```
❯ docker run --rm --entrypoint tini buildkite/agent:3.43.1-ubuntu echo hello world
hello world
```
should run without errors.

Typically, you would want `tini` to be the entrypoint, aka PID 1, as above, but if for some reason you need `sh` to be the entrypoint, then you should be able to do something like this:
```
❯ docker run --rm --entrypoint sh buildkite/agent:3.43.1-ubuntu -c 'exec tini echo hello world'
hello world
```

> We override the default entrypoint so we can inject linkerd2-proxy, which will wait for the Linkerd service mesh to start before allowing Buildkite to start, and tear the mesh down after Buildkite exits.

Thanks for sharing, that sounds pretty interesting! I imagine another work around would be to build another docker image and copy in the buildkite agent binary (`FROM buildkite/agent` or otherwise) so that you control where everything you need is.
