### ISSUE TITLE
Secret exports from cfn-env are not redacted

### ISSUE THREAD

**Issue by ChrisLane** [buildkite/agent#2061]
Elastic CI Stack for AWS: [v5.17.0](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.17.0)

We deploy all our infrastructure via AWS CDK and store our secrets in AWS Secrets Manager.
In our Buildkite bootstrap script, we alter the `/var/lib/buildkite-agent/cfn-env` to fetch and export our secrets from secrets manager, thus avoiding the need to create extra files in S3 to set our secret environment variables.

I have noticed that the output from cfn-env being run is not redacted according to the redaction rules and was hoping that this could be fixed.

Here's a screenshot of such output (manually redacted):
![undredacted-secrets](https://user-images.githubusercontent.com/925091/235122969-072e7144-5911-4b4b-a17a-8438cdbe3a93.png)
Blue values are redacted for the purpose of posting this publicly but the red value is also what I would expect Buildkite to have redacted.

**Comment by triarius** [comment]
Hi @ChrisLane, thanks for using the buildkite-agent and bringing this to our attention.

The redaction of values only works after the environment variables that contain those values have been exported for the first time. Furthermore, the redaction requires the [hook](https://buildkite.com/docs/agent/v3/hooks) that is exporting the variable to have completed before it knows the values to redact.

I assume you're using one of the functions in the `cfn-env` script, `set_unless_present` or `set_always` to create the secrets as environment variables. Unfortunately, those functions print out the values of their arguments BEFORE using them to create environment variables. Here's the body of the simpler of the two:
```
1	function set_always() {
2	    local target=$1
3	    local value=$2
4
5	    echo "export ${target}=\"${value}\""
6	    declare -gx "${target}=${value}"
7	}
```
The text you see in your screenshot is from the `echo` command in line 5 (or its equivalent for `set_unless_present`). If you passed in a secret value as the second argument, the buildkite-agent does not know whether it should redact the secret value until it is turned into an environment variable. This is because the redaction is based on the name of the environment variable associated to the secret value, and that association is not made until at least line 6. However, as I mentioned above, the design of the redaction also has to wait until the hook has completely finished execution.

While we could change the `cfn-env` script to not print these values, we don't want to do so without considering any impact on other customers that expect these to appear in the job log. So I think the simplest workaround in your case is to not use the function `set_always` or `set_unless_present`, and just use `export` or `declare -gx` to turn your secrets into environment variables instead.

However, it should be noted that the `cfn-env` script is sourced for more than just jobs. There are [scripts](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/6f2aecc350c12061efe6af9450e105fca6e1ee05/packer/linux/conf/buildkite-agent/scripts/stop-agent-gracefully#L5) on the elastic stack that are not related to running jobs that also sources the `cfn-env`. So if you only need these secrets for running jobs, I don't think this is the best place to put them. Instead, I recommend creating a [plugin](https://buildkite.com/docs/plugins) or modifying the [global environment hook](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/6f2aecc350c12061efe6af9450e105fca6e1ee05/packer/linux/conf/buildkite-agent/hooks/environment) instead.

**Comment by ChrisLane** [comment]
Thanks for the detailed response.

I will make some silent versions of the functions in that file and hopefully migrate to modifying the global hook.

**Comment by triarius** [comment]
Cool, I think this plugin could be useful for you too: https://github.com/seek-oss/aws-sm-buildkite-plugin
