### ISSUE TITLE
Timestamp misalignment in logs during `bazel run`

### ISSUE THREAD

**Issue by yi-lu** [buildkite/agent#2393]
We've observed a mismatch in the logged timestamps when executing a `bazel run` command. Specifically, the log's timestamp appears to only account for the build duration and not the actual run time of the binary.

When executing `bazel run //:xxx`, it internally performs
```
bazel build //:xxx
execution of the built binary ./bazel-out/.../bin/xxx
```
In our case the entire `bazel run` step takes approximately 3 minutes, but the Bazel log only reports the build time with message like `INFO: Elapsed time: 2.686s, Critical Path: 0.27s`. This indicates the actual build step took only 2 seconds, which is not accounting for the full duration of the `bazel run` command.

Due to this, the timestamp reported for the next step in the Buildkite log is misaligned. The next step's log timestamp assumes that  the previous step took only 2 seconds, disregarding the total run time of the bazel run.

e.g. if we have
```
stepA: bazel run //:xxx
stepB: something else
```
the starting time of stepB is incorrectly logged as ts+2s, instead of ts+3mins.

**Comment by DrJosh9000** [comment]
Hi @yi-lu, thanks for the report. Bazel is a little tricky since it likes to repeatedly overwrite its previous output. The raw job logs should have the timestamp of each line, and Buildkite usually displays the most timestamp associated with each line to display and compute header durations.

That said, "Elapsed time: ... Critical Path: ..." looks like output from Bazel itself. As much as the agent handles output from the jobs that are run (buffering and adding timestamps), it's not really responsible for what the jobs themselves print out.

Do you have a link to a job where this happened that we could look at?

**Comment by yi-lu** [comment]
To be clear I'm talking about the ANSI timestamp feature provided by Buildkite. 

![image](https://github.com/buildkite/agent/assets/13973239/932709ee-95c4-424d-ba7a-9137c84d889a)

Does this screenshot clarify things? The timestamp for the "Upload bazel logs & profiles" step incorrectly starts immediately after bazel build completes, without accounting for the duration of the actual bazel run. The subsequent line, "# No build events ..." probably marks the true completion time of the bazel run. This line is nearly instantaneous and wouldn't take ~3 minutes on its own.

**Comment by DrJosh9000** [comment]
It sounds like there could be an issue with the logic that interprets the ANSI timestamp codes from the job logs for display, but it's possible that it's an issue with the agent code that adds ANSI timestamps. It's difficult to say without comparing with a raw job log.

A link to an example job (such as the one in your screenshot) would be the most informative. I understand if that's not desirable information to put on a public GitHub issue - feel free to email support@buildkite.com and refer to this issue.

**Comment by yi-lu** [comment]
reached out through our support Slack channel separately from this thread

**Comment by DrJosh9000** [comment]
Thanks. Having looked at the log this does look like an edge case in the agent timestamp prefixer:

- Bazel writes `\n` followed by `ESC [0m`. Content after `\n` triggers the prefixer (writing the 13:05:16 CDT timestamp).
- Later, the script echoes `--- :page_facing_up: Upload bazel logs & profiles` at 13:08:08 CDT. But because Bazel started the new line already (not just `\n`, but more bytes afterwards), it doesn't get a new timestamp prefixed. 

In other words, the same "line" has content written to it at two different times by two different things. That's going to be a bit tricky to catch.

If this is the reason, a workaround would be to manually echo a blank line after Bazel has run. This would also help confirm the theory.

Perhaps the prefixer could skip adding a prefix until it sees _printable_ output, and not escapes like `ESC [0m`. Alternatively, we could add some kind of timer to the prefixer, that inserts a fresh timestamp onto the same line if the previous one is too far in the past (this would make it possible to see in the raw logs approximately when pieces of a slowly-written line were written).
