### ISSUE TITLE
Windows: Buildkite batch script crashes if the commit message contains special characters

### ISSUE THREAD

**Issue by fweikert** [buildkite/agent#2446]
From https://buildkite.com/bazel-trusted/bazel-release/builds/1306#018b4df2-a358-43b8-ae14-2962307e28b5:

```
Running batch script | 0s
-- | --
  | > C:\Users\b\AppData\Local\Temp\buildkite-script-237560845.bat
  | 'is' is not recognized as an internal or external command,
  | operable program or batch file.
  | 🚨 Error: The command exited with status 9009
  | user command error: exit status 9009
```

- Commit: https://github.com/bazelbuild/bazel/commit/e66a10f473ed853393061633e3803a8f71e47bff
- buildkite-agent/3.50.3.6503 (windows; amd64) on Windows Server 2019

Note that the commit message starts with `most likely a typo for the redirection (&>2 is >&2)`. The batch script crashes when setting `BUILDKITE_MESSAGE`, apparently due to not properly escaping the special characters.

I haven't tried updating the agent yet, but based on a quick look at `internal/job/executor.go` the relevant code doesn't seem to have changed between 3.50 and 3.57.

**Comment by DrJosh9000** [comment]
Hi @fweikert, thanks for the report. Bear with me while I work to understand what's happening here!

The nontrivial bits of Batch script in the agent are [the scriptwrapper](https://github.com/buildkite/agent/blob/224b3d50d6b54eb91bd03627d3e1aeb98a46fe4f/hook/scriptwrapper.go#L23-L30), and [writeBatchScript](https://github.com/buildkite/agent/blob/224b3d50d6b54eb91bd03627d3e1aeb98a46fe4f/internal/job/executor.go#L1045-L1074).

"Running batch script" only appears when [the executor uses `writeBatchScript`](https://github.com/buildkite/agent/blob/224b3d50d6b54eb91bd03627d3e1aeb98a46fe4f/internal/job/executor.go#L917C1-L918C1) to introduce a temporary batch script (evidently to work around some limitation with multi-line commands), but it looks like the temp script doesn't interfere with any env vars.

The agent should be passing variables to scripts/commands/hooks/plugins by using the usual Go interface (the `Env` field of [`exec.Cmd`](https://pkg.go.dev/os/exec#Cmd)) rather than inserting `set` statements.

The remaining explanation is that `%BUILDKITE_MESSGAGE%` is being used in the `command` of a step uploaded by `buildkite-agent pipeline upload`, without escaping or quotes, and it looks like that is the case. Specifically, I think [lines 232 and 263](https://github.com/bazelbuild/continuous-integration/blob/5a88d9670dcb4338c005f2a25edb70a5ca083a2a/pipelines/bazel-release.yml#L232C1-L232C56) of `bazel-release.yml` need some quotes:
```
set "BUILDKITE_MESSAGE=%BUILDKITE_MESSAGE:~0,1000%"
```

**Comment by meteorcloudy** [comment]
@DrJosh9000 Thanks for the debugging, we'll fix the script in https://github.com/bazelbuild/continuous-integration/pull/1767

**Comment by fweikert** [comment]
@DrJosh9000 thanks, and sorry for the confusion!
