### ISSUE TITLE
Enable Targeted Enforcement of Signed Pipelines

### ISSUE THREAD

**Issue by jmandel1027** [buildkite/agent#2898]
**Is your feature request related to a problem? Please describe.**

Our organization Block (Square, Cash App, TIDAL, Afterpay) has a large number of pipelines that dynamically upload steps. We would like to transition to Signed Pipelines. However we need to roll this out in a targeted fashion rather than [globally](https://buildkite.com/docs/agent/v3/signed-pipelines#enabling-signed-pipelines-on-your-agents-step-2-configure-the-agents
) across a given queue. 

Turning on this feature would be pretty disruptive and break many of our pipelines. 

**Describe the solution you'd like**

We need the Agent to give us the means to target what pipelines have enforced signing so that we can iteratively transition to signed pipelines. Ideally this setting could be a resource like so:

```hcl
resource "buildkite_pipeline_signing_key" "my_key" {
  pipeline_id =   buildkite_pipeline.pipeline.id
  jwks_file   = "/path/to/my/jwks.json"
  jwks_key_id = "my-key"
}
```

It would be even more optimal if we could make this work with KMS key alias's as well, but that might be out of scope for this particular feature request.

https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/data-sources/signed_pipeline_steps

**Describe alternatives you've considered**

We've considered a dedicated queue for handling the uploads, but it feels more than a bit like overkill for our situation. Having the ability to iteratively migrate towards this model would really be a major win on our side.

**Additional context**

**Comment by dabarrell** [comment]
Hey @jmandel1027! Thanks for raising this – glad to hear you're looking at signed pipelines. 

Signed pipelines serves as protection against a bad actor using Buildkite to dispatch malicious jobs, which means for it to be effective, there needs to be zero trust placed on Buildkite as a platform. That's the motivation behind signed pipelines being entirely configured by the agent.

If the agent allowed Buildkite to tell it not to enforce the signature for a given pipeline/job, we'd have to guarantee that that configuration (e.g. `validate_signature = false`) came from your organisation, which isn't something we can currently do.

While that might be possible in the future, it sounds like you're actively looking at this now. I've asked your Technical Account Manager to reach out to you to get some more details about your specific scenario - hopefully we can help you find a good way to roll it out smoothly for your org!

**Comment by dabarrell** [comment]
For anyone stumbling upon this, the `--verification-failure-behavior` flag (https://buildkite.com/docs/agent/v3/cli-start#verification-failure-behavior) is a useful tool for rolling out signed pipelines. It allows for setting an agent to warn mode, which will output log lines at the start of a job when it detects an invalid signature, but it won’t fail the job itself. We suggest setting it to warn mode initially, then flip from warn to block when they can see that the invalid signatures are resolved

I'm going to close this issue as acknowledgement that we're not going to be doing anything in this space that would help for pipeline-by-pipeline rollout, due to the reasons noted above
