### ISSUE TITLE
Configurable agent timeout

### ISSUE THREAD

**Issue by def-** [buildkite/agent#2969]
**Is your feature request related to a problem? Please describe.**
We have long-running jobs (> 24 hours), and are commonly seeing network problems causing "Agent Lost".

**Describe the solution you'd like**
If we could configure the timeout, agents would no longer get lost and we wouldn't have to retry those long test runs.

**Describe alternatives you've considered**
As a workaround we move tests back to AWS' us-east-1, but that is more expensive.

**Comment by DrJosh9000** [comment]
Hi @def- , thanks for raising this. I'd like to understand the problem a bit better - where are your agents running (describing this as ping time to us-east-1 is probably fine)? Do the network problems last longer than a few minutes?

I imagine the reason the network problems are leading to lost agents is because the agent heartbeat (usually once every 2 minutes) fails. Is that the timeout you would like to increase?

**Comment by def-** [comment]
The agents are running in Europe. There seem to be periods of intermediate network problems.

Yes, I'd like the possibility to allow the agent hearbeat to fail for a few consecutive minutes, which would reduce the need for us to rerun tests when the agent got lost.

**Comment by patrobinson** [comment]
@def- unfortunately this is a configuration we set in our backend, we wait 3 minutes for some communication from the agent before we declare it lost and cancel the job it's running. Please reach out to us at support@buildkite.com so we can understand a bit more about your use case and see if there's anything else we can help you with.

**Comment by def-** [comment]
I did that before and support told me to open an issue.

**Comment by patrobinson** [comment]
Thanks @def- , I'll follow this up and reply to your original ticket.
