### ISSUE TITLE
Skipping Build Steps with Existing Commits

### ISSUE THREAD

**Issue by whizzzkid** [buildkite/agent#3031]
**Is your feature request related to a problem? Please describe.**
Buildkite allows for `Skip builds with existing commits` however this does not work for many scenarios involving merge-queues, e.g. say we have deploy-trigger step which get triggered on merge to `main`, however if I enable this option, that step won't ever get triggered.

**Describe the solution you'd like**
What I would actually like is a way to create a build and skip steps that have already been run for a given commit.

**Describe alternatives you've considered**
Creating two different pipelines, one handles the merge-queues and other handles the deployment.

**Additional context**
Having a way to use skip conditionals in a way `BUILDKITE_PREVIOUSLY_BUILT=success` or a global way to only run steps which did not run on a given sha would be nice. I maybe missing a few scenarios but this will help.

**Comment by clbarrell** [comment]
Hi @whizzzkid,

I'm from the product team at Buildkite. This is great because merge queue support is something we're looking into at the moment. I think what would be best is if you contacted [support](mailto:support@buildkite.com) with a bit more information about your situation, a link to an example build, and exactly how you're finding the skip builds with existing commits not working for merge queues, so that we can better troubleshoot and understand what type of product improvement would help in your situation. We'll be able to discuss more useful information in private regarding your specific use of Buildkite than we would here :) 

Thanks,
Chris
