### ISSUE TITLE
Max command length in pipeline

### ISSUE THREAD

**Issue by edwinv** [buildkite/agent#334]
We are refactoring our CI scripts. Our goal is to minimize the number of extra scripts we need to run our test suite and call as much from the Buildkite pipeline file as possible.

When I include a command with 360 characters, the agents returns an error:

```
$ buildkite-agent meta-data exists buildkite:git:commit
rotating_light Buildkite Error: Failed to retrieve file information of "/buildkite/builds/1a1bbf025020/111111111/registry/export COMPOSE_PROJECT_NAME=1111111111111111111111111_632f5195854bf34bd4d7a37ed2eb26972015ca50_${BUILDKITE_PARALLEL_JOB} && docker-compose run --rm -e RAILS_ENV=test 1111111111111111111111111 -e BUILDKITE_PARALLEL_JOB=${BUILDKITE_PARALLEL_JOB} -e BUILDKITE_PARALLEL_JOB_COUNT=${BUILDKITE_PARALLEL_JOB_COUNT} bin/wait bin/cibuild && docker-compose stop && docker-compose rm --all -f" (stat /buildkite/builds/1a1bbf025020/11111111/registry/export COMPOSE_PROJECT_NAME=1111111111111111111111111_632f5195854bf34bd4d7a37ed2eb26972015ca50_${BUILDKITE_PARALLEL_JOB} && docker-compose run --rm -e RAILS_ENV=test 1111111111111111111111111 -e BUILDKITE_PARALLEL_JOB=${BUILDKITE_PARALLEL_JOB} -e BUILDKITE_PARALLEL_JOB_COUNT=${BUILDKITE_PARALLEL_JOB_COUNT} bin/wait bin/cibuild && docker-compose stop && docker-compose rm --all -f: file name too long)
```

There seems to be some kind of limit on the length of the command.

**Comment by keithpitt** [comment]
Thanks @edwinv! So the issue here is - we check to see if `$BUILDKITE_COMMAND` is a file on the filesystem, because we need to change the way we run random commands, and scripts within a repo. Golang seems to have an issue with checking for the existence of files, if the string is longer than the file path limit on the operating system.

We'll probably need a smarter way to figure out if it's a script or not! Perhaps we can do a `path.split` first or something to see if it's "file path" looking? Not sure!

**Comment by keithpitt** [comment]
This will be out in a new beta today!
