### ISSUE TITLE
Normalise upload/download paths with Windows

### ISSUE THREAD

**Issue by keithpitt** [buildkite/agent#354]
It shouldn't matter what sort of `/` you use on Windows `foo/bar.zip`or `foo\bar.zip` between the Agent API and the Agent itself it should be able to find the right artifact for you.

**Comment by ticky** [comment]
In addition, it appears that when we do upload artefacts with Windows paths, they download (on OS X, at least) as _that full path_, which is probably undesirable and also inconsistent.

Additionally, it appears that some artefact types (.msi in particular) have other manipulations added, somewhere between the Agent and downloading from s3

**Comment by lox** [comment]
Need to check that status of this after recent work I've done post v3 beta 33.

**Comment by lox** [comment]
Related to https://github.com/buildkite/agent/issues/96

**Comment by lox** [comment]
This still seems to be an issue.

**Comment by petemounce** [comment]
We get affected by this; the scenario is uploading a directory's worth (e.g. `**/results/*` that contains html, json etc) of HTML/JSON test-results into artifacts, where we use GCS behind an artifact proxy (for auth). I can see requests being made against paths containing `/` (http path separator) which will fail against GCS since the GCS objects are named with `\` inside them because the agent uploads them that way.
