### ISSUE TITLE
Improve github status integration (steps)

### ISSUE THREAD

**Issue by bforchhammer** [buildkite/agent#374]
Hello,

We quite like the option to "Create a commit status for each step" for github pull requests. We also really like emoticons. All this love leads to slightly strange "step names" on our PRs:

![buildkite-github-status-checks](https://cloud.githubusercontent.com/assets/434203/18062176/ff6694de-6e25-11e6-85eb-2e4d43afa2cd.png)

Is there any chance for these step names to be improved? So, if there's a step ":cherries: prospector/tests", can you strip emoticons and any non-ascii characters from the context string and use `prospector-tests` instead of `cherries-prospector-slash-tests` to github instead?

Thanks
Benedikt

**Comment by keithpitt** [comment]
Ah yeah, that old thing. We've actually gone through a few iterations of how the "Label to GitHub Status Text"  works. It's tricky because if you just use an `:rspec:` emoji for an test, you kinda want it to come through as `rspec`, but in your case, it doesn't come out working that well.

I have thought about just allowing peeps to customise the context, then if you don't like the defaults you can just use your own:

```
steps:
  - command: "prospector-tests.sh"
    github:
      status:
        context: "buildkite/%pipeline/prospector-tests"
```

I'm not entirely sure of the syntax, but perhaps something like that?

**Comment by bforchhammer** [comment]
> Ah yeah, that old thing.

Sorry if there's already an issue for discussing this... I couldn't find anything ;-)

> I have thought about just allowing peeps to customise the context, ...

That would definitely work!

Downside for us would be that it's a lot of repeated statements with bigger pipelines, e.g. if you have 10+ steps like we do at the moment that adds ~30 additional lines.

A different syntax with less overhead would be to simply add a machine-name field on the top-level:

    steps:
      - command: "prospector-tests.sh"
        name: :cherries: Prospector / Tests
        machine_name: prospector-tests

Would that work?

Alternatively, how about a generic way for configuring it, e.g.

    config:
      github:
        status:
          whitelist:
            - :rspec:
    steps:
      - command: "prospector-tests.sh"
        name: :cherries: Prospector / Tests

`whitelist` could also just support a regex... ;-)

**Comment by jgavris** [comment]
👍 We would also appreciate this (emojis and readable steps)!

**Comment by bluecmd** [comment]
:+1: Anyone managed to do this in a nice way?

**Comment by keithpitt** [comment]
👋 We're just doing some spring cleaning, and we're going to close this issue for now. Sorry we haven't gotten around to implementing this yet. If anyone wants this re-prioritised, please re-open the issue!

In the mean time, you can turn off the built in GitHub commit status updates, and roll your own using the GitHub API. It's a bit yucky...but at least you'll be able to set what ever context label + description you want!

**Comment by asford** [comment]
We've a situation where we'd like to post back two or three pipeline steps to Github, rather than pushing the full set of build steps. It would be very nice to have some degree of fine-grained control over the commit status postback. Including, perhaps, a custom name and a toggle over whether the step requires a status postback. 

It's seems like adding the status name as an *optional* configurable parameter would be a simple solution to the emoji-complexity problem. Rather than trying to infer the proper rules for formatting a non-ascii pipeline name you can rely on the consumer determining the correct format.

**Comment by deecewan** [comment]
Also keen for this. I think that doing hand-rolled statuses via the API is fraught with possible problems, like setting the status if the build is cancelled or if a failure happens in a place you're not expecting. Seems like the simplest fix is to have the status name configurable.

Disclosure: I haven't looked into it at all, but I'd be happy to PR this if it would be accepted. I don't know if the code to do that is open source tho.

**Comment by thesayyn** [comment]
Me and my team also rooting for this. It is such a mess to see something like this on the PR page.
