### ISSUE TITLE
git clean issues with invalid directory permissions

### ISSUE THREAD

**Issue by npaufler** [buildkite/agent#407]
Admittedly this is an edge case and only one that should come up when someone/something has done something wrong, but there is a case where the git clean setup (for preparing the build workspace between jobs) can get in an unusable state.

Example:
A fresh agent connects and is assigned a job. That job checks out the source code for the repository. One of the build steps makes a mistake and creates a directory two levels deep, puts one or more files in that directory, and then assigns bad permissions to deepest directory (0644). The next time that agent tries to run a job for the same pipeline, it will error during checkout because it can't clean the workspace.

For example, do the following within a git repository:
```
$ mkdir -p first/second
$ touch first/second/filename
$ chmod 0644 first/second
$ git clean -fxdq
warning: failed to remove first/
```

The big problem with this is that the agent then becomes poisoned and cannot run any more builds for that pipeline until that directory is manually removed/permissions fixed (or in our case, the agent is lifecycled out).

This is not something that should ever happen when you aren't doing something bad, but we ran into it when we encountered an issue with the CarrierWave gem that was somehow creating directories with the invalid permissions. We are fixing that problem by addressing the real problem (CarrierWave) but did want to point out this case.

I'm not sure if it's actually worth fixing (or how you'd go about doing so in any sane way), though, so mostly this is just here as a record of it.

**Comment by lox** [comment]
Have you encountered this subsequently @npaufler? It's tempting to extend the corrupted checkout detection in https://github.com/buildkite/agent/pull/556 and trigger a fresh checkout on certain errors like this.

**Comment by npaufler** [comment]
@lox We have not encountered it since but agree that approach probably makes sense here. Thanks!

**Comment by beydogan** [comment]
I'm having the same issue here when I'm trying to cache `node_modules` folder between docker-compose builds.

I have this entry in `docker-compose.yml` under the service;

```
    volumes:
      - ./:/app
      - node_modules:/node_modules
```

On second run of the agent, it fails to remove `node_modules` folder because its owned by `root`

```
drwxr-xr-x   3 buildkite-agent buildkite-agent  4096 Feb  1 10:23 .
drwxr-xr-x   3 buildkite-agent buildkite-agent  4096 Feb  1 10:16 ..
drwxr-xr-x 753 root            root            36864 Feb  1 10:22 node_modules
```

Any suggestions?

**Comment by shaneog** [comment]
I'm having this issue now, since I implemented recommendation number 3 from this Buildkite blog post: https://building.buildkite.com/5-ways-weve-improved-flakey-test-debugging-4b3cfb9f27c8

**Comment by lox** [comment]
The above two issues (@shaneog / @beydogan) sound like a classic docker host-mounted volume permissions issues to me. Unfortunately this is a quirk of docker that we can at best work around. 

What is happening is if you mount a host volume into a docker container and then write a file in it, docker will give the file on the host system the uid/gid that the docker daemon is running as. This is commonly root. If this file is in a checkout directory, then when the buildkite-agent user comes along later to clean up the file, it can't.

Consider: 

```
docker run -v "$PWD:/pwd" --rm -it alpine:latest mkdir /pwd/llamas
ls -al llamas
```

You should see that the `llamas` directory is owned by either `root`, or whatever user docker is run by. 

There are a few solutions to this. 

1. User namespace remapping to the same user that your buildkite-agent is running as: https://docs.docker.com/engine/security/userns-remap/. This is what we do in the elastic stack and it works great, and has the upside of locking down the docker socket too. Highly recommended 👌 

2. Run a script before or after builds that resets permissions. You can do this either via docker (because it runs as root) or via sudo. The elastic stack used to do this, but it was annoying. See https://github.com/buildkite/elastic-ci-stack-for-aws/blob/v2.3.4/packer/conf/buildkite-agent/scripts/fix-buildkite-agent-builds-permissions and https://github.com/buildkite/elastic-ci-stack-for-aws/blob/v2.3.4/packer/conf/buildkite-agent/sudoers.conf

I hope that helps! Beyond that, might I highly recommend the elastic stack, we've been solving these problems for you for many years now :) 

I'm going to close this issue!

**Comment by shaneog** [comment]
Thanks @lox. I'll try one of those options.

> Beyond that, might I highly recommend the elastic stack, we've been solving these problems for you for many years now :)

Please bring it to Google Cloud Platform!!

**Comment by beydogan** [comment]
FYI, User namespace remapping did the trick for me, it works as expected now.

**Comment by lox** [comment]
> Please bring it to Google Cloud Platform!!

Fair call 😅

**Comment by beydogan** [comment]
It took me a while and several emails between me and @lox to setup docker based Buildkite agent environment, so I created an Ansible playbook for setting it up easily. It lets you to setup a server in 10-15 mins.

See;
https://github.com/beydogan/buildkite-agent-playbook

**Comment by shaneog** [comment]
@lox Following on from this, just letting you know that the user namespace remapping doesn't work when you use multi-stage builds such as with the following Dockerfile.
See https://github.com/moby/moby/issues/34645

You may need to add this warning to the Elastic Stack, or figure out a workaround.

I think this might rule-out user namespace remapping for me, and I may have to use scripts.


**Dockerfile**
```
# ---- Base Node ----
FROM ruby:2.5.0-slim AS base

RUN mkdir -p /app

WORKDIR /app

COPY . .

# ---- Release ----
FROM base AS release

WORKDIR $INSTALL_PATH

COPY --from=base /usr/local/bundle /usr/local/bundle

RUN rm -rf /usr/local/bundle/cache

COPY . .

```

**docker-compose.yml**
```
services:
  app:
    build:
      context: .
      target: base
  release:
    build:
      context: .
      target: release
```

**Comment by lox** [comment]
@shaneog that's an odd one! We use multi-stage builds all the time. The issue seems to be talking about using hardcoded uid's and gid's, are you sure yours is the same thing? Feel free to open an issue in https://github.com/buildkite/elastic-ci-stack-for-aws/issues if so and I'll look into it.

**Comment by shaneog** [comment]
@lox It was my stupidity - I only had a single line in the `/etc/subgid` and `/etc/subuid` instead of 2.
I copied from the Elastic CI Stack and from @beydogan's playbook and it's working now.

Thanks for all your help!!

**Comment by shaneog** [comment]
Sadly I was wrong (note to self: don't do serious things at 1am on Sunday), and this still doesn't work with multi-stage builds.

@lox I went as far as to create an AWS account and create a stack to prove that it's an issue even on the Elastic CI Stack. 
@beydogan I also tried your Ansible playbooks and it's an issue there also.
