### ISSUE TITLE
buildkite-agent.cfg token - file path vs integer

### ISSUE THREAD

**Issue by erikng** [buildkite/agent#458]
It would be great if we could set the token to a file path instead of the token integer.

We want to control our cfg file via chef, but this means we have to expose the token in our code repo. Having it link to a file would allow us to deploy the secret, but dynamically control the config file in chef.

**Comment by toolmantim** [comment]
Hey Erik! Interesting! With Chef, it's not possible to embed/compose configs as files? Because the agent config itself is a file, it just has the token inside of it?

**Comment by erikng** [comment]
If we embed the file, our token is inside of it.

We have an internal secret system that we call via chef to write out the file currently, but the limitation is chef doesn't know what the file structure of the config should look like. If we could give the config a path to a file that just contains the token, chef can obtain that secret (and doesn't need to know what the secret is) and we can make changes to our config file as needed.

**Comment by toolmantim** [comment]
Right! So you'd have to store the entire config file itself inside a "secret" in your secret store? Because there's no way to gsub/sed the config with the secret?

**Comment by erikng** [comment]
Yeah, exactly.

**Comment by toolmantim** [comment]
Thanks for clarifying @erikng!

@keithpitt @sj26 is this something you see as okay to add to the agent? If so, I can look at adding support. I think it also fits well with Kubernetes and Docker Swarm secrets too, as they're also files on the filesystem.

**Comment by sj26** [comment]
Hmm, I guess we could. This feels like a very specific use case which could have many other solutions which don't require adding such a specific new feature into the core agent. For example, the way I might do this would be to write out a systemd drop-in which sources an environment file placed somewhere by a secrets system, like:

```
# /etc/systemd/system/buildkite-agent.service.d/secrets.conf
[Service]
EnvironmentFile=/etc/buildkite-agent/secrets
```

```
# /etc/buildkite-agent/secrets
BUILDKITE_AGENT_TOKEN=abc123
```

Would something like that work?

**Comment by toolmantim** [comment]
Is using environment variables for sensitive data considered an anti-pattern these days? Same as command line args? I thought it was, and have been wondering how we can encourage people to move away from specifying the agent token as an env for cases like Docker. I thought this would be the same kind of use case. But I might have over-generalised there.

**Comment by sj26** [comment]
Heh, I think my answer to that is a pretty hefty "it depends."

Sorry for the brain dump, but some thoughts:

Command line arguments shouldn't contain secrets because most processes on the system can see the command line of other processes, including arguments. Most systems won't allow quite the same level of access to a process' launch environment, you need to be the same user or a super user to see the environment data. This is not necessarily the runtime environment, that's an implementation detail as the program is free to treat "environment" however it likes, 'nix only dictates an interface at process boundaries. But even if passed in a file or something else the secret is still available in said files or in process memory with the same user or super user restrictions, so it's just security theatre. But there's definitely an argument that security through obscurity is worth in some cases.

One of the other arguments is that environment is propagated to subprocesses, so secrets can be leaked. This is how memory exploits in mini-magick might compromised your payment provider credentials. But we're pretty careful about sanitizing the environment before invoking the bootstrap and command processes. They can't see the agent registration token directly in their environment. (They could still fish for it in the parent process memory, though.)

Running builds in docker containers is the best protection. This keeps the agent process and it's filesystem completely separated, and should be enough security for most. There are still exploits here, like when running within Kubernetes then containers within the same pod share execution environment, but that's probably beyond this discussion.

So, basically, I don't think in this case it's a huge deal to pass the agent token to the agent as an environment var.

All that said, I don't mind how you want to take this. I just don't want to introduce too many ways to do the same thing in the same codebase, potentially complicating things down the road.

**Comment by keithpitt** [comment]
@erikng how have you solved this for other services you manage via chef? I'm probably totally wrong, and I can't quite remember how Chef works, but don't you create template files with ERB or something and substitute values into them as they are written onto a server?

Also you mentioned:

> but the limitation is chef doesn't know what the file structure of the config should look like.

Any chance we _can_ teach it what the file structure is? :)

**Comment by keithpitt** [comment]
I did some googling for any established patterns on this, but I couldn't seem to find any (I looked at tools like Scout and the Datadog agent) - maybe there are some other tools I can look at it to see how they solve this problem?

**Comment by erikng** [comment]
The main issue comes down to this. If you manage a file it looks at what is essentially a hash. Chef will look at each and every line of a config file and if it doesn't match the expected values, it will correct those areas.

Because of this, we have a few options:
1. Store the entire config in a secret store and continually drop it down each chef run since chef cannot understand the content of the config. (this could lead into a race condition)
2. Store the entire config in chef and be able to change the token whenever we want.
3. Store the entire config and let buildkite read the token via a file/environment variable/etc. (this is what I want)

Option 3 allows us to use our tool [Knox](https://github.com/pinterest/knox) to get the secret.

I don't see another way.

**Comment by sj26** [comment]
Sorry I'm not super familiar with chef, but here's a chef cook book which seems to be able to build a buildkite agent config file from options in your chef config, and interpolating a token from an encrypted data bag. I presume you might be able to source this token from other tools like Knox as well? Is this kinda what you're trying to do?

https://github.com/bendrucker/buildkite-cookbook

**Comment by lox** [comment]
👋 After some lengthy discussion, we've decided we want to keep these sorts of concerns out of the config file. Let us know if we can help further with ways to generate the config file with the values you want in it.

**Comment by Jircs1** [comment]
great
