### ISSUE TITLE
More streamlined checkout options for phabricator repos

### ISSUE THREAD

**Issue by KevinGrandon** [buildkite/agent#504]
Currently for Phabricator the first thing checkout does is: `git fetch -v origin <commit>`

If the commit is not found, it fetches all tags with:
`git fetch -v origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*`

This fetch can take a long time for larger repos and in the case of phabricator should not be necessary. Instead we would like to be able to directly fetch the tag with something like:
`git fetch origin "${BUILDKITE_BRANCH}:"${BUILDKITE_BRANCH}"`

I think we may be able to do this with a custom checkout hook, but since it may be beneficial to everyone using Phabricator, an improvement in the agent would be nice.

**Comment by toolmantim** [comment]
Sorry you're having troubles with this.

I think it's because your Phabricator git server doesn't supporting [fetching a specific git commit](https://stackoverflow.com/questions/14872486/retrieve-specific-commit-from-a-remote-git-repository/30701724#30701724), which is making [this](https://github.com/buildkite/agent/blob/6a9608216cb395cda21ce42cf6f50f2437fc78f3/bootstrap/bootstrap.go#L1058) return a non-zero status. I don't think is specific to Phabricator at all… any git server that doesn't support that, but has lots of tags, would have this performance problem :(

One workaround for now is to use the bootstrap’s [custom refspec support](https://github.com/buildkite/agent/blob/6a9608216cb395cda21ce42cf6f50f2437fc78f3/bootstrap/bootstrap.go#L1025-L1030).

You can't set the `BUILDKITE_REFSPEC` environment variable in a hook, but you can do it by wrapping the bootstrap. Which is nicer and easier than overriding the `checkout` hook.

Here's an example, which I've tested and it seems to work okay:
https://gist.github.com/toolmantim/43de11658602b3f7c0e1921fcea7ac5f

Would that suit as a workaround for now?

I just opened PR #517 to see if we could instead just add a `fetch` hook, rather than having to rely on this custom refspec support and bootstrap wrapper.

**Comment by KevinGrandon** [comment]
Thank you for the detailed response. We are indeed running an older git server so that makes sense why it isn't able to fetch the commit. I'm going to put in a request to upgrade this server, as well as implement the bootstrap script in parallel.

**Comment by KevinGrandon** [comment]
We have a workaround for now, so going to close this. Hopefully folks might find this useful in the future if they stumble across this ticket.
