### ISSUE TITLE
Feature request: Scheduled pipelines without creating another pipeline

### ISSUE THREAD

**Issue by mbreedveld** [buildkite/agent#594]
I have a feature request (I think it does not exists yet), upload another pipeline in a scheduled build so you can perform e.g. deep testing and deep security checks which you don’t want to do in each build. Currently, we have to create an extra pipeline for this.

**Comment by lox** [comment]
Out of interest, what are the downsides of creating another pipeline for specific types of tests? We quite often have pipelines for deployment, or extra testing, etc.

**Comment by mbreedveld** [comment]
It's more an administrative optimization so we can group builds by repository e.g. frontend is one pipeline which contains different types of builds.

**Comment by lox** [comment]
I guess the downside of that limitation is that you miss out on being able to use Trigger steps to create builds in other pipelines. This is often preferable to just using a single monolithic pipeline because you can at a glance see when the last build of that particular type ran, and you can independently re-run them without having to re-run all of the previous steps.

**Comment by mbreedveld** [comment]
I did not know that feature, probably we should move to triggered builds. I would definitely still help if we can group pipelines.

# Groups

### Frontend

   - Test pipeline
   - Deploy pipeline
   - Etc.

### Backend

   - Test pipeline
   - Deploy pipeline
   - Etc.

**Comment by lox** [comment]
In that case, I'm going to close this one in favour of https://github.com/buildkite/feedback/issues/129.
