### ISSUE TITLE
-x as a default git clean flag

### ISSUE THREAD

**Issue by mallyvai** [buildkite/agent#644]
Hello BK team! I would like to propose that ```-x``` as a default flag supplied to git clean.

I believe that ```git clean``` is there to make subsequent runs on the same host independent. Right now, we have a situation where docker volumes are sending build artifacts to an underlying directory that's sometimes used by subsequent jobs, and there's a collision with one of these artifacts.

I think we're going to solve this with git-clean-flags metadata for now, but I really believe that -x is a sensible default here :) 

Thank you!
Vaibhav

**Comment by lox** [comment]
Totally agree 🙌🏻 It's the default in our 3.x series of agents. See https://github.com/buildkite/agent/blob/master/packaging/github/linux/buildkite-agent.cfg#L40. Because it's a pretty big behaviour change we decided it wasn't something we could change in the 2.x series. 

Follow https://github.com/buildkite/agent/milestone/2 for the stable release of the 3.x series. 

I'm going to close this, feel free to re-open if I've missed something!
