### ISSUE TITLE
RPM package overwrites systemd unit file

### ISSUE THREAD

**Issue by gtirloni** [buildkite/agent#747]
When the RPM is installed or updated, it overwrites the `/usr/lib/systemd/system/buildkite-agent.service` and `/usr/lib/systemd/system/buildkite-agent@.service` files, causing any modifications to be lost.

An update should create .rpmsave or .rpmnew files and not modify in place.

**Comment by timn** [comment]
You should put your override in /etc/systemd/system, rather than modify files directly in /usr/lib/systemd. You can also use drop-ins, a good documentation is available, for example, at CoreOS: https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html
So I think buildkite is doing the right thing, it is rather how overrides on your systems are handled that could be improved. Hope that helps.

**Comment by gtirloni** [comment]
@timn thanks
