### ISSUE TITLE
Feature request: S3 upload to custom endpoints (eg Minio)

### ISSUE THREAD

**Issue by zegl** [buildkite/agent#857]
Hey,

It would be nice if it was possible for to add support for uploading artifacts to self hosted S3-clones, such as [Minio](https://minio.io/).

This would make it possible to run buildkite-agent in environments that are partly blocked from the internet, and thus does not have S3 access.

This feature is available [in the AWS SDK](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/).

**Comment by keithpitt** [comment]
@zegl you should be able to do this now! https://buildkite.com/docs/agent/v3/cli-artifact#using-your-own-private-aws-s3-bucket

Can you let me know if that fits your needs?

**Comment by muhlba91** [comment]
@keithpitt hi, i stumbled upon the same requirement as i'd like to host my artifacts in a private minio instance.
however, for this i need to set the S3 endpoint url (e.g. like in the cache plugin: https://github.com/gencer/cache-buildkite-plugin#s3-compatible-providers).
unfortunately, i wasn't able to find a configuration reference for providing a custom endpoint url - could you maybe point me into the right direction?

**Comment by moskyb** [comment]
hi @muhlba91! I'm 85% sure that we already support minio as an artifact storage backend, because it basically just pretends to be S3. You should be able to specify the upload destination in [the same way as you would a custom s3 bucket](https://buildkite.com/docs/agent/v3/cli-artifact#using-your-private-aws-s3-bucket), but using your minio path instead of an S3 path.

if that doesn't work, reach out to support@buildkite.com and we'd be happy to help you out :)

**Comment by nightah** [comment]
@moskyb apologies for bumping a closed issue however, I think I can comfortably say that MinIO isn't supported out of the box.

At first, when following the docs at [Using your private AWS S3 bucket](https://buildkite.com/docs/agent/v3/cli-artifact#using-your-private-aws-s3-bucket) I ran into a [nil ptr](https://buildkite.com/authelia/authelia/builds/18361#01860b53-d2ca-4438-b6d3-9dcd738cf013). With some local debugging it looked like that was because the `region` was unset and the fallback logic not being entirely foolproof, manually setting it to any value got past that nil ptr.

What I noticed next was that the actual URL to construct the path to upload artifacts was incorrect, you can observe this [here](https://buildkite.com/authelia/authelia/builds/18362#01860bef-988a-494e-98a3-75f69bb535c2). It looks like `BUILDKITE_S3_ACCESS_URL` isn't utilised in how I interpret the docs to read.

Happy to lodge a separate issue or email for further discussion I'm not sure if you have access to all of the values that are being exposed via the agent hooks, just not really sure how to proceed at this stage.
