### ISSUE TITLE
Prepend BUILDKITE_BINPATH to PATH iff not already in the PATH

### ISSUE THREAD

**Issue by w4-sjcho** [buildkite/agent#952]
It seems like the buildkite agent is prepending BUILDKITE_BINPATH to PATH:
https://github.com/buildkite/agent/blob/master/bootstrap/bootstrap.go#L402-L406

This is causing problems when we want to change, for example, the default python to be `/opt/conda/bin/python` instead of `/usr/bin/python`, when the buildkite agent is installed in `/usr/bin` (e.g. buildkite is installed as apt package).

Even if we set `PATH=/opt/conda/bin:/usr/bin` to make sure that `/opt/conda/bin/python` is tried first, the agent changes to `PATH=/usr/bin:/opt/conda/bin:/usr/bin`, so `/usr/bin/python` is used.

It would be nice if the agent only prepend the PATH if it is not already there, or just append the PATH at the end.

**Comment by lox** [comment]
Sorry you've run into problems with this @w4-sjcho, we do that so that calls to `buildkite-agent` will always refer to the same binary as `buildkite-agent start` was invoked with, otherwise folks run into subtle bugs where they have different versions on their system.

One fix for you might be moving the `buildkite-agent` binary to its own directory? E.g `/usr/local/buildkite-agent/bin/buildkite-agent` or similar?

**Comment by w4-sjcho** [comment]
Yes that works, and is the workaround I'm using right now.

**Comment by keithduncan** [comment]
This should be fixed with https://github.com/buildkite/agent/pull/1465 and will be included in the next release!
