### ISSUE TITLE
Add template file for distros that use systemd

### ISSUE THREAD

**Issue by harrietgrace** [buildkite/agent#958]
It would be great if we had systemd template files for running multiple agents in the distros that use systemd. This was originally suggested by @lox here: https://github.com/buildkite/docs/issues/186 😊

**Comment by keithduncan** [comment]
Hi @harrietgrace, our current recommendation is to use the [spawn](https://buildkite.com/docs/agent/v3/configuration#spawn) configuration option, instead of systemd template units, to run multiple buildkite-agents per host. I’m going to close this but let us know if you’d still like to see systemd template files added for another use case we haven’t considered :bow:
